In [1]:
import pandas_market_calendars as mcal
import pandas as pd

In [3]:
options = pd.read_csv("data/options.csv")
options = options[
    [
        col
        for col in options.columns
        if "tdays_to" not in col
    ]
]

In [4]:
options.head()

,date_current,ticker,expiration_date,days_to_expiry,option_id,option_type,strike_price,bid_price,option_price,ask_price,implied_volatility,volume,open_interest,stock_price,dividend_yield
0,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C200,C,200.0,107.3,100.57,107.44,272.46,0,10,307.07,1.81
1,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C205,C,205.0,102.3,94.82,102.44,258.59,0,0,307.07,1.81
2,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C210,C,210.0,97.3,89.83,97.44,244.92,0,0,307.07,1.81
3,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C215,C,215.0,92.3,84.84,92.44,231.45,0,0,307.07,1.81
4,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C225,C,225.0,82.3,77.19,82.44,205.47,0,2,307.07,1.81

In [5]:
nyse = mcal.get_calendar('NYSE')
min_date = options.date_current.min()
max_date = options.expiration_date.max()

In [6]:
schedule = nyse.schedule(start_date=min_date, end_date=max_date)
trading_days = mcal.date_range(schedule, frequency="1D").tolist()
trading_days = [str(day)[:10] for day in trading_days]

In [7]:
def get_trading_days(x):
    try:
        i = trading_days.index(x[0])
        j = trading_days.index(x[1])
        return j - i
    except Exception as e:
        print(e)
        return None

pairs = options[['date_current', 'expiration_date']].drop_duplicates(ignore_index=True)
pairs['tdays_to_expiry'] = pairs.apply(get_trading_days, axis=1)
pairs = pairs.dropna()

In [8]:
options = options.merge(pairs, on=['date_current', 'expiration_date'], how='inner')
options.to_csv("data/options.csv", index=False)

In [10]:
options.head()

,date_current,ticker,expiration_date,days_to_expiry,option_id,option_type,strike_price,bid_price,option_price,ask_price,implied_volatility,volume,open_interest,stock_price,dividend_yield,tdays_to_expiry
0,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C200,C,200.0,107.3,100.57,107.44,272.46,0,10,307.07,1.81,2
1,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C205,C,205.0,102.3,94.82,102.44,258.59,0,0,307.07,1.81,2
2,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C210,C,210.0,97.3,89.83,97.44,244.92,0,0,307.07,1.81,2
3,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C215,C,215.0,92.3,84.84,92.44,231.45,0,0,307.07,1.81,2
4,2019-11-06,SPY,2019-11-08,2,SPY 2019-11-08 C225,C,225.0,82.3,77.19,82.44,205.47,0,2,307.07,1.81,2